### ISSUE TITLE
Unable to change user on same IdP

### ISSUE THREAD

**Issue by AJamesPhillips** [inrupt/pod-browser#336]
In an incognito tab:

1. go to broker.pod.inrupt.com/ click login
2. get redirected to podbrowser.inrupt.com/ click "sign in", get redirected to auth.inrupt.com/
3. sign in as user1, get redirected to podbrowser.inrupt.com/
4. click the "log out" button in the top right under the menu
5. get redirected to podbrowser.inrupt.com/ click "sign in", enter into podbrowser.inrupt.com/

In step 5 the only other option is "SIGN IN WITH OTHER PROVIDER".  If I choose `https://broker.pod.inrupt.com/` I get the following error message:

```
{"error":"invalid_grant","error_description":"Invalid redirect_uri"}
```

from: https://broker.pod.inrupt.com/authorization?client_id=https%3A%2F%2Fpodbrowser.inrupt.com%2Fapi%2Fapp&redirect_uri=https%3A%2F%2Fpodbrowser.inrupt.com%2Flogin&response_type=code&scope=openid%20webid&state=6<...deleted...>d&code_challenge=i<...deleted...>M&code_challenge_method=S256&response_mode=query

Is there a way to change my user?

**Comment by AJamesPhillips** [comment]
IF it helps the motivation for this is when developing an application it's often useful to change users to see what the state is in a different pod of a different user etc.  I don't think this would often be used by regularly users though saying that until there is a more advanced auth function then I could imagine people using Solid pod's and applications similar to other tool suites which allow you to:
1. see which user you currently are
2. see a list of other users you can be from a menu
3. change which user you are from the menu

Examples include various Google applications and Twitter but obviously many more.

**Comment by kevin-inrupt** [comment]
Thanks for the background. I certainly understand the need as I often need to switch users when testing applications. I think I've just go used to using Incognito mode, or implementing Roles (in TestCafe) when doing end-2-end testing.

**Comment by ThisIsMissEm** [comment]
We've tracked this in our internal issue tracker, however, it requires SDK changes to be supported. I'm going to close this issue, as it's known and cannot be fixed at this time, unfortunately.
