### ISSUE TITLE
Signing in as user1 then user2 results in trying to go to user1

### ISSUE THREAD

**Issue by AJamesPhillips** [inrupt/pod-browser#337]
In trying to recreate #334 not in incognito I'm getting a different error now.

I think I was signed in as `ajp2` (but it's hard to tell) and then I went to http://broker.pod.inrupt.com/ I chose `ajp` and it redirected me to podbrowser.inrupt.com .  Before I could tell if this new error was occurring I put `http://broker.pod.inrupt.com/` into the address bar, went there and clicked signin again (I think) but now the podbrowser.inrupt.com is stuck trying to get me ajp2 despite logging in as ajp.

Steps to recreate:

1. go to https://podbrowser.inrupt.com/login and choose signin
2. choose to login as user1
3. leave the browser tab to marinate for an hour or two?
4. come back and find it has logged you out / session expired
5. go to https://podbrowser.inrupt.com/login and choose signin
6. choose to login as **user2** (2 not user1)
7. observe podbrowser says `You don't have access to this resource: https://pod.inrupt.com/user1/.`

Again **I think** it's related to this issue https://github.com/inrupt/solid-client-authn-js/issues/1473

https://user-images.githubusercontent.com/526509/131146246-fb2b4d71-bc62-457d-9aa3-f803ad4c0b31.mp4

**Comment by NSeydoux** [comment]
This sounds very much like it is related to the issue you link to @AJamesPhillips, I'll investigate to see if it is indeed the case and how this can be mitigated.

**Comment by ThisIsMissEm** [comment]
This should be resolved, as long as you completely log out of the IdP in between, otherwise the IdP will treat you as having wanted to login as `user1` instead of `user2`, though other redirect issues have been fixed in #437
