### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by AJamesPhillips** [inrupt/pod-browser#342]
I signed in and clicked on a folder.

I was viewing my files.  I pressed back in the browser to get back to the top level and accidentally pressed back a second time.

I think it presented me with the page at https://podbrowser.inrupt.com/login

I pressed login / signin a second time.  It then proceeds to error / loop.

Clearing the localstorage for podbrowser.inrupt.com seemed to allow me to correctly login.

This is a video before I cleared localstorage showing the looping behaviour.

https://user-images.githubusercontent.com/526509/131997641-820c8eeb-df43-4246-9675-1095dfa37649.mp4

**Comment by VirginiaBalseiro** [comment]
@AJamesPhillips thank you for reporting this! We're having trouble reproducing it following your instructions, would you mind testing it out again and seeing if you can provide us with more details? 
Thanks so much in advance!

**Comment by AJamesPhillips** [comment]
In trying to recreate it I think I found a different failure mode but not sure so posting under the same issue.


https://user-images.githubusercontent.com/526509/132561666-749cb657-3a75-44ac-81f2-bffc8d3c8e61.mp4

**Comment by ThisIsMissEm** [comment]
This should be fixed now, as we completely overhauled login in #437
