### ISSUE TITLE
Session seems incredibly short

### ISSUE THREAD

**Issue by AJamesPhillips** [inrupt/pod-browser#345]
The length of the session seems very short, i.e. I almost always return to the tab (of podbrowser.inrupt.com) and find it has logged me out forcing me to hunt for the signin button, wait for auth.inrupt.com to load, click the user name field, choose my user name, click login, wait longer for the page to redirect, then reload, and then reload my data.  10 seconds + 4 clicks each time is not a great user experience.  Is the session intentionally short or is this a bug?  If it is intentional then I understand the pod might one day contain sensitive information but so does a lot of my other web storage systems and logging me out is not very good protection at all... browser password autocomplete means it's trivial for someone else to regain a session if they have access to my computer.  Is there a plan to allow a longer time limit?  Is the time limit static or is it based on inactivity?

Thanks for your consideration, I appreciate this might not be a pod browser specific issue and might instead be a auth.inrupt.com issue?

**Comment by ThisIsMissEm** [comment]
I think this should now be improved, there'll still be a redirect flow between PodBrowser and your IdP on first load, but it usually remember that you granted access.

**Comment by ThisIsMissEm** [comment]
Closing this as fixed, as further reports have not been filed.
