### ISSUE TITLE
Navigating to a url with path does not update url after login

### ISSUE THREAD

**Issue by AJamesPhillips** [inrupt/pod-browser#372]
I tried to go to: https://podbrowser.inrupt.com/resource/https%3A%2F%2Fpod.inrupt.com%2Fajp%2Fpublic%2F

It had logged me out and after logging back in it return me to https://podbrowser.inrupt.com and showed the correct folder but it did not change the url to match the folder it was in.  It should have shown: https://podbrowser.inrupt.com/resource/https%3A%2F%2Fpod.inrupt.com%2Fajp%2Fpublic%2F

**Comment by ThisIsMissEm** [comment]
This should now be fixed thanks to #437, if it's still an issue, please reply and we can reopen this issue
