### ISSUE TITLE
Redirect loop on 404

### ISSUE THREAD

**Issue by AJamesPhillips** [inrupt/pod-browser#461]
https://podbrowser.inrupt.com/2022-03-25_tradingeconomics.com_uk_natural_gas.png

**Comment by AJamesPhillips** [comment]
Happend twice with the same link.  I could see it flashing between `https://podbrowser.inrupt.com/?code=` something and `https://podbrowser.inrupt.com/` and the url above.  On trying to click the above URL it then went straight to the 404 page before I could capture a video of it.

**Comment by AJamesPhillips** [comment]
I was at this URL: https://pod.inrupt.com/ajp/public/2022-03-25_tradingeconomics.com_uk_natural_gas.png
I clicked back in my browser.  I can't remember now but pretty sure I clicked on a bookmark to: https://podbrowser.inrupt.com/resource/https%3A%2F%2Fpod.inrupt.com%2Fajp%2Fpublic%2F

The session had already expired, after what seemed like less than 5 minutes, so I had to log in again.
It then caught me in the same redirect loop.


https://user-images.githubusercontent.com/526509/160176137-69a7a3f1-71d9-4433-b14c-7e388f863d83.mp4



On visiting this url: https://pod.inrupt.com/ajp/public/2022-03-25_tradingeconomics.com_uk_natural_gas.png it then started to work fine again.

**Comment by ThisIsMissEm** [comment]
Can verify this is a bug, will raise it with the team

**Comment by ThisIsMissEm** [comment]
This appears to now be fixed. Thanks for reporting.
