### ISSUE TITLE
Could not found some predicates from `person.shex`

### ISSUE THREAD

**Issue by danielbakas** [inrupt/pod-browser#521]
Hi there! I was constructing my profile at [`https://id.danielbakas.com`](https://id.danielbakas.com) by adding all properties in [`person.shex`](https://github.com/inrupt/pod-browser/blob/main/shapes/profile/person.shex) and found that some predicates cannot be found in their namespace (do not exist).

Here's the list:
- [`vcard:phone`](http://www.w3.org/2006/vcard/ns#phone)
- [`solid:preferredObjectPronoun`](http://www.w3.org/ns/solid/terms#preferredObjectPronoun)
- [`solid:preferredRelativePronoun`](http://www.w3.org/ns/solid/terms#preferredRelativePronoun)
- [`solid:preferredSubjectPronoun`](http://www.w3.org/ns/solid/terms#preferredSubjectPronoun)

**Comment by ThisIsMissEm** [comment]
These are from the new webid-profiles work, so currently not defined by published spec, as far as I know. @VirginiaBalseiro can give more information. For the `vcard:phone` predicate, you're correct that it's "wrong", though I'm not sure if we'll fix it.

I'm going to close as the person.shex isn't fully used yet by pod-browser.
